# LGE Optimus MACH.
# Generated By D.H.Kim. the TEAM ONEIRIC WORKSHOP.
# http://anycookie.tistory.com/
# http://drsmart.tistory.com/   (Team Site)
# anicookie@naver.com

USE_CAMERA_STUB := false

# inherit from the proprietary version
-include vendor/lge/lu3000/BoardConfigVendor.mk



#+++++++ PLATFORM SETTING +++++++ [

TARGET_BOARD_PLATFORM := omap3

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true
#TARGET_PROVIDES_INIT_RC := true
OMAP_ENHANCEMENT := true
BOARD_USES_UBOOT := true
TARGET_BOOTLOADER_BOARD_NAME := lu3000

#+++++++ PLATFORM SETTING +++++++ ]




#+++++++ OVERLAY SETTING +++++++ [
ifdef OMAP_ENHANCEMENT
COMMON_GLOBAL_CFLAGS += -DOMAP_ENHANCEMENT -DTARGET_OMAP3
endif
COMMON_GLOBAL_CFLAGS += -DOVERLAY_NUM_REQBUFFERS=12
#+++++++ OVERLAY SETTING +++++++ ]

#+++++++++ CAMERA & OMX ++++++++ [
BOARD_USES_TI_CAMERA_HAL := true
HARDWARE_OMX := true
ifdef HARDWARE_OMX
OMX_JPEG := true
OMX_VENDOR := ti
OMX_VENDOR_INCLUDES := \
   hardware/ti/omx/system/src/openmax_il/omx_core/inc \
   hardware/ti/omx/image/src/openmax_il/jpeg_enc/inc
OMX_VENDOR_WRAPPER := TI_OMX_Wrapper
BOARD_OPENCORE_LIBRARIES := libOMX_Core
BOARD_OPENCORE_FLAGS := -DHARDWARE_OMX=1
BOARD_CAMERA_LIBRARIES := libcamera
endif
#+++++++++ CAMERA & OMX ++++++++ [



#********* KERNEL COMPILIZATION OPTION ********* <
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_NO_RECOVERY := true
#\o/ hahahahahahaha!
#BOARD_KERNEL_CMDLINE := mem=511M init=/init videoout=omap24xxvout omap_vout_mod.video1_numbuffers=6 omap_vout_mod.vid1_static_vrfb_alloc=y vram=7M,0x9f800000 omapfb.vram=0:5M rs=c console=/dev/null
#BOARD_KERNEL_BASE := 0x20000000
#BOARD_KERNEL_PAGESIZE := 2048
#********* KERNEL COMPILIZATION OPTION ********* >



#--------- Partition SETTING -------- [
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x25800000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x15040000
BOARD_FLASH_BLOCK_SIZE := 0x00040000
#--------- Partition SETTING -------- ]



#--------- ETC SETTING --------- [
BOARD_NEEDS_CUTILS_LOG := true
BOARD_EGL_CFG := device/lge/p970/configs/egl.cfg
#--------- ETC SETTING --------- ]



#--------- BLUETOOTH OPTIONS --------- [
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_HAVE_FM_RADIO := true
COMMON_GLOBAL_CFLAGS += -DHAVE_FM_RADIO
#--------- BLUETOOTH OPTIONS --------- ]


#--------- Audio Setting ---------- [
BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
TARGET_PROVIDES_LIBAUDIO := true
BOARD_USES_TI_OMAP_MODEM_AUDIO := true
#--------- Audio Setting ---------- ]


#----- WiFi/BT Module Setting ----- [
# 수정필요, 마하 순정 파일에 맞게 커스터마이징 해야함.
BOARD_WPA_SUPPLICANT_DRIVER := CUSTOM
BOARD_WLAN_DEVICE           := wl1271
BOARD_SOFTAP_DEVICE         := wl1271
WPA_SUPPLICANT_VERSION      := VER_0_6_X
WIFI_DRIVER_MODULE_PATH     := "/system/lib/modules/mwlan_arpp.ko"
WIFI_DRIVER_MODULE_ARG      := ""
WIFI_DRIVER_MODULE_NAME     := "tiwlan_drv"
#WIFI_EXT_MODULE_PATH        := "/system/lib/modules/sdio.ko"
#WIFI_EXT_MODULE_NAME        := "sdio"
#WIFI_FIRMWARE_LOADER        := "wlan_loader"
#----- WiFi/BT Module Setting ----- ]

